# Generated by Django 2.0.2 on 2018-03-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180302_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='昵称')),
                ('email', models.EmailField(max_length=254, verbose_name='电子邮件')),
                ('comment', models.TextField(verbose_name='评论')),
            ],
            options={
                'db_table': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
