# Generated by Django 2.0.2 on 2018-03-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog_view_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_time'], 'verbose_name_plural': '博客'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
    ]
