# Generated by Django 2.0.2 on 2018-03-15 12:51

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180313_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=martor.models.MartorField(verbose_name='内容'),
        ),
    ]
