# Generated by Django 2.0.2 on 2018-03-07 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0005_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('email', models.EmailField(max_length=254, verbose_name='电子邮件')),
                ('comment', models.TextField(verbose_name='评论')),
                ('create_time', models.DateTimeField(verbose_name='时间')),
                ('commentinblog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog')),
            ],
        ),
    ]
